# Header

menu:
  主页: /
  工具使用: /tags/工具使用
  技术学习: /tags/技术学习
  育儿经: /tags/育儿经

# SubNav
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /github_blog/

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /github_blog/avatar.jpg

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  friends: '友链'
  aboutme: '关于我'

friends:
  seafile: http://maobaolong.f3322.net/seafile
  home: http://maobaolong.f3322.net:9999
  herHome: http://maobaolong.gicp.net:9999
  个人博客: http://maobaolong.f3322.net/blog

aboutme: 多学多记<br><br>多分享<br>谢谢大家
